services:
  physical-dev:
    build: .
    ports:
      - "8000:8080"
    environment:
      CLIENT_ID: "com.spencerhartland.Physical"
      CLIENT_SECRET_FILE: /run/secrets/client_secret
      VALIDATION_URL: "https://appleid.apple.com/auth/token"
      PUBLIC_KEY_URL: "https://appleid.apple.com/auth/keys"
      ISSUER: "https://appleid.apple.com"
      PUBLIC_KEY_ALGORITHM: "RS256"
    secrets:
      - client_secret
secrets:
  client_secret:
    file: ./client_secret.txt