services:
  prod:
    image: physical-api
    build: .
    environment:
      CLIENT_SECRET_FILE: /run/secrets/client_secret
      PRIVATE_KEY_FILE: /run/secrets/private_key
      ENCRYPTION_PASSWORD_FILE: /run/secrets/encryption_password
    secrets:
      - client_secret
      - private_key
      - encryption_password
  dev:
    image: physical-api
    ports:
      - "8000:8080"
    build: .
    environment:
      CLIENT_SECRET_FILE: /run/secrets/client_secret
      PRIVATE_KEY_FILE: /run/secrets/private_key
      ENCRYPTION_PASSWORD_FILE: /run/secrets/encryption_password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    secrets:
      - client_secret
      - private_key
      - encryption_password

secrets:
  client_secret:
    file: ./support/secrets/client_secret.txt
  private_key:
    file: ./support/secrets/private_key.p8
  encryption_password:
    file: ./support/secrets/encryption_password.txt